/* Generated By:JavaCC: Do not edit this line. ConciseLangConstants.java */
package concise.lang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConciseLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DELIMITER = 7;
  /** RegularExpression Id. */
  int ASSIGN = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int MULTI = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int MODULUS = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int NOT_EQUAL = 15;
  /** RegularExpression Id. */
  int LCB = 16;
  /** RegularExpression Id. */
  int RCB = 17;
  /** RegularExpression Id. */
  int TERNARY = 18;
  /** RegularExpression Id. */
  int STR = 19;
  /** RegularExpression Id. */
  int COND = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int DISPLAY = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int INTEGER = 25;
  /** RegularExpression Id. */
  int STRING_LITERAL = 26;
  /** RegularExpression Id. */
  int IDENTIFIER = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\".\"",
    "\":\"",
    "\"\\\'\"",
    "\"_\"",
    "\"^\"",
    "\"~\"",
    "\"/\"",
    "\"=\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"$\"",
    "\"!\"",
    "\",\"",
    "\"|\"",
    "\"view\"",
    "<TRUE>",
    "<FALSE>",
    "<INTEGER>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
  };

}
